apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cilium-operator
  namespace: kube-system
  labels:
    io.cilium/app: operator
    name: cilium-operator
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
