#!/bin/sh -e

limit=86400 # 1 day
now=$(date +%s)

sessions=$(loginctl list-sessions --no-legend | sed -e 's/^ *//g' | cut -f 1 -d ' ')
for session in $sessions
do
  timestamp=$(loginctl show-session -p Timestamp --value $session)
  target=$(date +%s --date "$timestamp")
  diff=$(( $now - $target ))
  if [ $diff -gt $limit ]; then
    echo "kill session:"
    loginctl show-session $session
    echo
    loginctl kill-session --signal 9 $session
  fi
done
