#!/bin/sh -e

limit=$(echo "3600 * 24 * 1" | bc) # 1 day
sessions=$(loginctl list-sessions --no-legend | sed -e 's/^ *//g' | cut -f 1 -d ' ')

for session in $sessions
do
  timestamp=$(loginctl show-session -p Timestamp --value $session)
  now=$(date +%s)
  target=$(date +%s --date "$timestamp")
  diff=$(( $now - $target ))
  if [ $diff -gt $limit ]; then
    echo "kill session:"
    loginctl show-session $session
    echo
    loginctl kill-session $session
  fi
done
