package generator

const artifactSetTemplate = `// Code generated by generate-artifacts. DO NOT EDIT.
// +build {{.Tag}}

package neco

var CurrentArtifacts = ArtifactSet{
	Images: []ContainerImage{
{{- range $image := .Images}}
 			{{$image.MarshalGo}},
{{end -}}
	},
 	Debs: []DebianPackage{
{{- range $deb := .Debs}}
 			{{$deb.MarshalGo}},
{{end -}}
	},
 	CoreOS: {{.CoreOS.MarshalGo}},
}
`
