apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: internet-egress
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unbound
    spec:
      # system priority class cannot be specified for pods in namespaces
      # other than kube-system as of k8s 1.12.
      # see https://github.com/kubernetes/kubernetes/pull/65593
      #priorityClassName: system-cluster-critical
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node.cybozu.io/cluster-not-ready
          effect: NoExecute
          operator: Exists
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - unbound
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - unbound
                topologyKey: "cke.cybozu.com/rack"
      serviceAccountName: unbound
      containers:
        - name: unbound
          image: ghcr.io/cybozu/unbound
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/unbound/unbound.conf
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound
              readOnly: true
            - name: temporary-volume
              mountPath: /tmp
          ports:
            - containerPort: 1053
              name: dns
              protocol: UDP
            - containerPort: 1053
              name: dns-tcp
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsGroup: 10000
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 1053
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 1053
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 6
        - name: exporter
          image: ghcr.io/cybozu/unbound_exporter
          imagePullPolicy: IfNotPresent
          args:
            # empty string = don't use cert
            - --unbound.ca=
            - --unbound.cert=
          ports:
            - containerPort: 9167
              name: metrics
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsGroup: 10000
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: config-volume
          configMap:
            name: unbound
            items:
              - key: unbound.conf
                path: unbound.conf
              - key: root.hints
                path: root.hints
        - name: temporary-volume
          emptyDir: {}
