apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - account.yaml
  - configmap.yaml
  - deployment.yaml
  - pdb.yaml
  - service.yaml
images:
  - name: ghcr.io/cybozu/unbound
    newTag: 1.18.0.2
  - name: ghcr.io/cybozu/unbound_exporter
    newTag: 0.4.4.2
