apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: unbound-pdb
  namespace: internet-egress
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
