apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: internet-egress
spec:
  selector:
    app.kubernetes.io/name: unbound
  ports:
    - name: dns
      port: 53
      targetPort: 1053
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 1053
      protocol: TCP
