#!/bin/sh -e

mkdir -p /var/lib/textfile-collector
SYSTEM_TIME=$(docker exec chrony chronyc -c tracking | awk -F',' '{print $5}')

printf '# TYPE chrony_monitor_tracking_system_time gauge\nchrony_monitor_tracking_system_time %s\n' ${SYSTEM_TIME} > /var/lib/textfile-collector/chrony-monitor.prom.$$
mv /var/lib/textfile-collector/chrony-monitor.prom.$$ /var/lib/textfile-collector/chrony-monitor.prom
