#!/bin/bash -e

set -o pipefail

mkdir -p /var/lib/textfile-collector
SYSTEM_TIME=$(docker exec chrony chronyc -c tracking | awk -F',' '{print $5}')
METRIC=chrony_monitor_tracking_system_time_seconds

printf '# TYPE %s gauge\n%s %s\n' ${METRIC} ${METRIC} ${SYSTEM_TIME} > /var/lib/textfile-collector/chrony-monitor.prom.$$
mv /var/lib/textfile-collector/chrony-monitor.prom.$$ /var/lib/textfile-collector/chrony-monitor.prom
