#!/bin/sh

ok=false
for i in $(seq 60); do
    sleep 1
    if docker exec setup-hw true; then
        ok=true
        break
    fi
done

if [ $ok = false ]; then
    echo "setup-hw container is not getting ready"
    exit 2
fi

# setup-hw container resets iDRAC at startup.
# Wait here to avoid the reset from occurring while the tool is running.
sleep 60

docker exec setup-hw setup-hw
RET=$?

if [ $RET -eq 10 ]; then
    sudo reboot
    exit 0
fi

exit $RET
