#!/bin/sh -e

for i in $(seq 20); do
    rm -f /opt/sbin/node_exporter
    if curl -sfSL -o /opt/sbin/node_exporter {{ MyURL }}/api/v1/assets/node_exporter; then
        break
    fi
    sleep 5
done

chmod a+x /opt/sbin/node_exporter
