#!/bin/sh -e

curl -sfSL -o /opt/sbin/sabakan-cryptsetup {{ MyURL }}/api/v1/assets/%%cryptsetup%%
chmod a+x /opt/sbin/sabakan-cryptsetup

mkdir -p /etc/systemd/system/sabakan-cryptsetup.service.d/
if /usr/bin/systemd-detect-virt -v >/dev/null; then \
    cat >/etc/systemd/system/sabakan-cryptsetup.service.d/10-env.conf <<EOF
[Service]
Environment='DISK_NAME_PATTERN=virtio-pci-0000:00:07.0'
EOF
else
    cat >/etc/systemd/system/sabakan-cryptsetup.service.d/10-env.conf <<EOF
[Service]
Environment='DISK_NAME_PATTERN=*-nvme-* *-ata-* *-sas-*'
EOF
fi

systemctl daemon-reload
