#!/bin/sh

# list failed unit names
# limit to 300 bytes because whole length of tags must be < 512 bytes.
systemd_units_failed="$(systemctl list-units --state=failed --no-legend --plain --full | cut -d' ' -f1 | head --bytes=300)"

docker exec -i serf serf tags \
       -set uptime="$(uptime -p)" \
       -set systemd-units-failed="${systemd_units_failed}"
