#!/bin/sh -e

{{ if ne (Metadata "external_ip_address_block") "" }}
# Restrict access from the outside if the external IP address block has been specified.
iptables -t filter -N PROTECT_GLOBAL
iptables -t filter -A PROTECT_GLOBAL ! -d {{ Metadata "external_ip_address_block" }} -j RETURN
iptables -t filter -A PROTECT_GLOBAL -p tcp -m multiport --dports 80,443 -j RETURN
iptables -t filter -A PROTECT_GLOBAL -p udp -m multiport --dports 80,443 -j RETURN
iptables -t filter -A PROTECT_GLOBAL -j DROP
iptables -t filter -I INPUT -j PROTECT_GLOBAL
{{ end }}
