#!/bin/sh -e

mkdir -p /etc/neco

for i in $(seq 120); do
    if curl -sfSL -o /etc/neco/bmc-user.json {{ MyURL }}/api/v1/assets/bmc-user.json; then
        break
    fi
    rm -f /etc/neco/bmc-user.json
    sleep 5
done
