#!/bin/sh -e

BIRD_IMAGE_ID=$(/usr/bin/rkt fetch --insecure-options=image {{ MyURL }}/api/v1/assets/cybozu-bird.aci)
UBUNTU_DEBUG_IMAGE_ID=$(/usr/bin/rkt fetch --insecure-options=image {{ MyURL }}/api/v1/assets/cybozu-ubuntu-debug.aci)

mkdir -p /etc/systemd/system/bird.service.d
cat <<EOF >/etc/systemd/system/bird.service.d/env.conf
[Service]
Environment=BIRD_IMAGE_ID=$BIRD_IMAGE_ID
Environment=UBUNTU_DEBUG_IMAGE_ID=$UBUNTU_DEBUG_IMAGE_ID
EOF

systemctl daemon-reload
