#!/bin/sh -e

for i in $(seq 20); do
    rm -f /opt/sbin/containerd
    if curl -sfSL -o /opt/sbin/containerd {{ MyURL }}/api/v1/assets/containerd; then
        break
    fi
    sleep 5
done

for i in $(seq 20); do
    rm -f /opt/sbin/containerd-shim
    if curl -sfSL -o /opt/sbin/containerd-shim {{ MyURL }}/api/v1/assets/containerd-shim; then
        break
    fi
    sleep 5
done

for i in $(seq 20); do
    rm -f /opt/sbin/containerd-shim-runc-v1
    if curl -sfSL -o /opt/sbin/containerd-shim-runc-v1 {{ MyURL }}/api/v1/assets/containerd-shim-runc-v1; then
        break
    fi
    sleep 5
done

for i in $(seq 20); do
    rm -f /opt/sbin/containerd-shim-runc-v2
    if curl -sfSL -o /opt/sbin/containerd-shim-runc-v2 {{ MyURL }}/api/v1/assets/containerd-shim-runc-v2; then
        break
    fi
    sleep 5
done

for i in $(seq 20); do
    rm -f /opt/sbin/k8s-runc
    if curl -sfSL -o /opt/sbin/k8s-runc {{ MyURL }}/api/v1/assets/k8s-runc; then
        break
    fi
    sleep 5
done

for i in $(seq 20); do
    rm -f /opt/bin/ctr
    if curl -sfSL -o /opt/bin/ctr {{ MyURL }}/api/v1/assets/ctr; then
        break
    fi
    sleep 5
done

for i in $(seq 20); do
    rm -f /opt/bin/crictl
    if curl -sfSL -o /opt/bin/crictl {{ MyURL }}/api/v1/assets/crictl; then
        break
    fi
    sleep 5
done

for i in $(seq 20); do
    rm -f /opt/bin/nerdctl
    if curl -sfSL -o /opt/bin/nerdctl {{ MyURL }}/api/v1/assets/nerdctl; then
        break
    fi
    sleep 5
done

chmod a+x /opt/sbin/containerd
chmod a+x /opt/sbin/containerd-shim
chmod a+x /opt/sbin/containerd-shim-runc-v1
chmod a+x /opt/sbin/containerd-shim-runc-v2
chmod a+x /opt/sbin/k8s-runc
chmod a+x /opt/bin/ctr
chmod a+x /opt/bin/crictl
chmod a+x /opt/bin/nerdctl
