apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: coild
  annotations:
    cke.cybozu.com/rank: "2500"
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 35%
