apiVersion: v1
kind: ServiceAccount
metadata:
  name: squid
  namespace: internet-egress
automountServiceAccountToken: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: internet-egress
  name: psp:squid
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["squid"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: internet-egress
  name: squid:psp:squid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:squid
subjects:
- kind: ServiceAccount
  name: squid
  namespace: internet-egress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: squid
  namespace: internet-egress
data:
  squid.conf: |-
    acl neco_network src 10.64.0.0/12
    # Only allow cachemgr access from localhost
    http_access allow manager localhost
    http_access deny manager
    http_access allow neco_network
    http_access deny all
    http_port 3128
    access_log stdio:/var/log/squid/access.log
    pid_filename "none"
    cache_dir aufs /var/spool/squid 50000 16 256
    coredump_dir /var/spool/squid
    cache_mem 6 GB
    maximum_object_size_in_memory 100 MB
    maximum_object_size 100 MB
    detect_broken_pconn on
    forwarded_for delete
    httpd_suppress_version_string on
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-unbound
  namespace: internet-egress
data:
  unbound.conf: |
    server:
      do-daemonize: no
      interface: 0.0.0.0
      interface-automatic: yes
      access-control: 10.64.0.0/12 allow
      chroot: ""
      username: ""
      directory: "/etc/unbound"
      logfile: ""
      use-syslog: no
      log-time-ascii: yes
      log-queries: yes
      log-replies: yes
      log-local-actions: yes
      log-servfail: yes
      rrset-roundrobin: yes
      minimal-responses: yes
      extended-statistics: yes
      rrset-cache-size: 256m
      msg-cache-size: 256m
      pidfile: "/tmp/unbound.pid"
      infra-host-ttl: 60
      prefetch: yes
      root-hints: "/etc/unbound/root.hints"
    remote-control:
      control-enable: yes
      control-interface: 127.0.0.1
      control-use-cert: no
  root.hints: |
    ;       This file holds the information on root name servers needed to
    ;       initialize cache of Internet domain name servers
    ;       (e.g. reference this file in the "cache  .  <file>"
    ;       configuration file of BIND domain name servers).
    ;
    ;       This file is made available by InterNIC
    ;       under anonymous FTP as
    ;           file                /domain/named.cache
    ;           on server           FTP.INTERNIC.NET
    ;       -OR-                    RS.INTERNIC.NET
    ;
    ;       last update:     November 14, 2018
    ;       related version of root zone:     2018111402
    ;
    ; FORMERLY NS.INTERNIC.NET
    ;
    .                        3600000      NS    A.ROOT-SERVERS.NET.
    A.ROOT-SERVERS.NET.      3600000      A     198.41.0.4
    A.ROOT-SERVERS.NET.      3600000      AAAA  2001:503:ba3e::2:30
    ;
    ; FORMERLY NS1.ISI.EDU
    ;
    .                        3600000      NS    B.ROOT-SERVERS.NET.
    B.ROOT-SERVERS.NET.      3600000      A     199.9.14.201
    B.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:200::b
    ;
    ; FORMERLY C.PSI.NET
    ;
    .                        3600000      NS    C.ROOT-SERVERS.NET.
    C.ROOT-SERVERS.NET.      3600000      A     192.33.4.12
    C.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:2::c
    ;
    ; FORMERLY TERP.UMD.EDU
    ;
    .                        3600000      NS    D.ROOT-SERVERS.NET.
    D.ROOT-SERVERS.NET.      3600000      A     199.7.91.13
    D.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:2d::d
    ;
    ; FORMERLY NS.NASA.GOV
    ;
    .                        3600000      NS    E.ROOT-SERVERS.NET.
    E.ROOT-SERVERS.NET.      3600000      A     192.203.230.10
    E.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:a8::e
    ;
    ; FORMERLY NS.ISC.ORG
    ;
    .                        3600000      NS    F.ROOT-SERVERS.NET.
    F.ROOT-SERVERS.NET.      3600000      A     192.5.5.241
    F.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:2f::f
    ;
    ; FORMERLY NS.NIC.DDN.MIL
    ;
    .                        3600000      NS    G.ROOT-SERVERS.NET.
    G.ROOT-SERVERS.NET.      3600000      A     192.112.36.4
    G.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:12::d0d
    ;
    ; FORMERLY AOS.ARL.ARMY.MIL
    ;
    .                        3600000      NS    H.ROOT-SERVERS.NET.
    H.ROOT-SERVERS.NET.      3600000      A     198.97.190.53
    H.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:1::53
    ;
    ; FORMERLY NIC.NORDU.NET
    ;
    .                        3600000      NS    I.ROOT-SERVERS.NET.
    I.ROOT-SERVERS.NET.      3600000      A     192.36.148.17
    I.ROOT-SERVERS.NET.      3600000      AAAA  2001:7fe::53
    ;
    ; OPERATED BY VERISIGN, INC.
    ;
    .                        3600000      NS    J.ROOT-SERVERS.NET.
    J.ROOT-SERVERS.NET.      3600000      A     192.58.128.30
    J.ROOT-SERVERS.NET.      3600000      AAAA  2001:503:c27::2:30
    ;
    ; OPERATED BY RIPE NCC
    ;
    .                        3600000      NS    K.ROOT-SERVERS.NET.
    K.ROOT-SERVERS.NET.      3600000      A     193.0.14.129
    K.ROOT-SERVERS.NET.      3600000      AAAA  2001:7fd::1
    ;
    ; OPERATED BY ICANN
    ;
    .                        3600000      NS    L.ROOT-SERVERS.NET.
    L.ROOT-SERVERS.NET.      3600000      A     199.7.83.42
    L.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:9f::42
    ;
    ; OPERATED BY WIDE
    ;
    .                        3600000      NS    M.ROOT-SERVERS.NET.
    M.ROOT-SERVERS.NET.      3600000      A     202.12.27.33
    M.ROOT-SERVERS.NET.      3600000      AAAA  2001:dc3::35
    ; End of file
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: squid
  namespace: internet-egress
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: squid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: squid
    spec:
      # system priority class cannot be specified for pods in namespaces
      # other than kube-system as of k8s 1.12.
      # see https://github.com/kubernetes/kubernetes/pull/65593
      #priorityClassName: system-cluster-critical
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 127.0.0.1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - squid
              topologyKey: "cke.cybozu.com/rack"
      serviceAccountName: squid
      containers:
        - name: squid
          image: {{ .squid }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/spool/squid
              name: cache
            - mountPath: /etc/squid
              name: config
          ports:
           - name: proxy
             containerPort: 3128
             protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - SETUID
                - SETGID
              drop:
                - all
            readOnlyRootFilesystem: true
          readinessProbe:
            tcpSocket:
              port: 3128
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 3128
            periodSeconds: 1
            initialDelaySeconds: 10
            failureThreshold: 6
        - name: unbound
          image: {{ index . "cke-unbound" }}
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/unbound/unbound.conf
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound
              readOnly: true
            - name: temporary-volume
              mountPath: /tmp
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 53
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 53
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 6
      volumes:
        - name: cache
          emptyDir: {}
        - name: config
          configMap:
            name: squid
            items:
              - key: squid.conf
                path: squid.conf
        - name: config-volume
          configMap:
            name: local-unbound
            items:
              - key: unbound.conf
                path: unbound.conf
              - key: root.hints
                path: root.hints
        - name: temporary-volume
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: squid
  namespace: internet-egress
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: squid
  ports:
    - protocol: TCP
      nodePort: 30128
      port: 3128
      targetPort: 3128
