apiVersion: v1
kind: ServiceAccount
metadata:
  name: unbound
  namespace: internet-egress
automountServiceAccountToken: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound
  namespace: internet-egress
data:
  unbound.conf: |
    server:
      do-daemonize: no
      interface: 0.0.0.0
      port: 1053
      interface-automatic: yes
      access-control: 10.64.0.0/12 allow
      chroot: ""
      username: ""
      directory: "/etc/unbound"
      logfile: ""
      use-syslog: no
      log-time-ascii: yes
      log-queries: yes
      log-replies: yes
      log-local-actions: yes
      log-servfail: yes
      rrset-roundrobin: yes
      minimal-responses: yes
      extended-statistics: yes
      rrset-cache-size: 256m
      msg-cache-size: 256m
      pidfile: "/tmp/unbound.pid"
      infra-host-ttl: 60
      prefetch: yes
      root-hints: "/etc/unbound/root.hints"
    remote-control:
      control-enable: yes
      control-interface: 127.0.0.1
      control-use-cert: no
  root.hints: |
    ;       This file holds the information on root name servers needed to
    ;       initialize cache of Internet domain name servers
    ;       (e.g. reference this file in the "cache  .  <file>"
    ;       configuration file of BIND domain name servers).
    ;
    ;       This file is made available by InterNIC
    ;       under anonymous FTP as
    ;           file                /domain/named.cache
    ;           on server           FTP.INTERNIC.NET
    ;       -OR-                    RS.INTERNIC.NET
    ;
    ;       last update:     November 14, 2018
    ;       related version of root zone:     2018111402
    ;
    ; FORMERLY NS.INTERNIC.NET
    ;
    .                        3600000      NS    A.ROOT-SERVERS.NET.
    A.ROOT-SERVERS.NET.      3600000      A     198.41.0.4
    A.ROOT-SERVERS.NET.      3600000      AAAA  2001:503:ba3e::2:30
    ;
    ; FORMERLY NS1.ISI.EDU
    ;
    .                        3600000      NS    B.ROOT-SERVERS.NET.
    B.ROOT-SERVERS.NET.      3600000      A     199.9.14.201
    B.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:200::b
    ;
    ; FORMERLY C.PSI.NET
    ;
    .                        3600000      NS    C.ROOT-SERVERS.NET.
    C.ROOT-SERVERS.NET.      3600000      A     192.33.4.12
    C.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:2::c
    ;
    ; FORMERLY TERP.UMD.EDU
    ;
    .                        3600000      NS    D.ROOT-SERVERS.NET.
    D.ROOT-SERVERS.NET.      3600000      A     199.7.91.13
    D.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:2d::d
    ;
    ; FORMERLY NS.NASA.GOV
    ;
    .                        3600000      NS    E.ROOT-SERVERS.NET.
    E.ROOT-SERVERS.NET.      3600000      A     192.203.230.10
    E.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:a8::e
    ;
    ; FORMERLY NS.ISC.ORG
    ;
    .                        3600000      NS    F.ROOT-SERVERS.NET.
    F.ROOT-SERVERS.NET.      3600000      A     192.5.5.241
    F.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:2f::f
    ;
    ; FORMERLY NS.NIC.DDN.MIL
    ;
    .                        3600000      NS    G.ROOT-SERVERS.NET.
    G.ROOT-SERVERS.NET.      3600000      A     192.112.36.4
    G.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:12::d0d
    ;
    ; FORMERLY AOS.ARL.ARMY.MIL
    ;
    .                        3600000      NS    H.ROOT-SERVERS.NET.
    H.ROOT-SERVERS.NET.      3600000      A     198.97.190.53
    H.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:1::53
    ;
    ; FORMERLY NIC.NORDU.NET
    ;
    .                        3600000      NS    I.ROOT-SERVERS.NET.
    I.ROOT-SERVERS.NET.      3600000      A     192.36.148.17
    I.ROOT-SERVERS.NET.      3600000      AAAA  2001:7fe::53
    ;
    ; OPERATED BY VERISIGN, INC.
    ;
    .                        3600000      NS    J.ROOT-SERVERS.NET.
    J.ROOT-SERVERS.NET.      3600000      A     192.58.128.30
    J.ROOT-SERVERS.NET.      3600000      AAAA  2001:503:c27::2:30
    ;
    ; OPERATED BY RIPE NCC
    ;
    .                        3600000      NS    K.ROOT-SERVERS.NET.
    K.ROOT-SERVERS.NET.      3600000      A     193.0.14.129
    K.ROOT-SERVERS.NET.      3600000      AAAA  2001:7fd::1
    ;
    ; OPERATED BY ICANN
    ;
    .                        3600000      NS    L.ROOT-SERVERS.NET.
    L.ROOT-SERVERS.NET.      3600000      A     199.7.83.42
    L.ROOT-SERVERS.NET.      3600000      AAAA  2001:500:9f::42
    ;
    ; OPERATED BY WIDE
    ;
    .                        3600000      NS    M.ROOT-SERVERS.NET.
    M.ROOT-SERVERS.NET.      3600000      A     202.12.27.33
    M.ROOT-SERVERS.NET.      3600000      AAAA  2001:dc3::35
    ; End of file

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: internet-egress
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unbound
    spec:
      # system priority class cannot be specified for pods in namespaces
      # other than kube-system as of k8s 1.12.
      # see https://github.com/kubernetes/kubernetes/pull/65593
      #priorityClassName: system-cluster-critical
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node.cybozu.io/cluster-not-ready
          effect: NoExecute
          operator: Exists
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - unbound
              topologyKey: "cke.cybozu.com/rack"
      serviceAccountName: unbound
      containers:
        - name: unbound
          image: {{ index . "cke-unbound" }}
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/unbound/unbound.conf
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound
              readOnly: true
            - name: temporary-volume
              mountPath: /tmp
          ports:
            - containerPort: 1053
              name: dns
              protocol: UDP
            - containerPort: 1053
              name: dns-tcp
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsGroup: 10000
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 1053
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 1053
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 6
        - name: exporter
          image: {{ index . "cke-unbound_exporter" }}
          imagePullPolicy: IfNotPresent
          args:
            # empty string = don't use cert
            - --unbound.ca=
            - --unbound.cert=
          ports:
            - containerPort: 9167
              name: metrics
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsGroup: 10000
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: config-volume
          configMap:
            name: unbound
            items:
              - key: unbound.conf
                path: unbound.conf
              - key: root.hints
                path: root.hints
        - name: temporary-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: internet-egress
spec:
  selector:
    app.kubernetes.io/name: unbound
  ports:
    - name: dns
      port: 53
      targetPort: 1053
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 1053
      protocol: TCP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: unbound-pdb
  namespace: internet-egress
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
