#!/bin/sh

set -e

http_proxy=http://10.0.49.3:3128/
https_proxy=http://10.0.49.3:3128/

cat > /etc/apt/sources.list <<EOF
deb http://linux.yz.yamagata-u.ac.jp/ubuntu/ bionic main restricted universe multiverse
deb http://linux.yz.yamagata-u.ac.jp/ubuntu/ bionic-updates main restricted universe multiverse
deb http://linux.yz.yamagata-u.ac.jp/ubuntu/ bionic-security main restricted universe multiverse
EOF

env http_proxy=$http_proxy apt-get update -o Acquire::Retries=5
env http_proxy=$http_proxy apt-get install -o Acquire::Retries=5 -y --no-install-recommends jq ca-certificates freeipmi-tools
apt-get clean

touch /tmp/auto-config-done
