#!/bin/bash

SUDO=$(which sudo)
SCRIPT_DIR=$(cd $(dirname $0);pwd)
SSH_CONFIG=${SCRIPT_DIR}/ssh_config
IDENTITY_FILE=${SCRIPT_DIR}/dctest_key

chmod 600 ${IDENTITY_FILE}
${SUDO} ip netns exec operation ssh -F ${SSH_CONFIG} -i ${IDENTITY_FILE} $@
