#!/bin/sh -u

PART_TYPE=f800
PART_NAME=ceph-osd

# The following command creates a partition with gdisk. 
# Its type is $PART_TYPE and its name is $PART_NAME.
GDISK_CMD=$(cat << EOS
o
y
n



$PART_TYPE
c
$PART_NAME
w
y
EOS
)

is_target_device() {
    DEV=$(basename $1)
    if [ $DEV = 'vda' ] || [ $DEV = 'vdb' ]; then
        # in the case of qemu's system disks, enter here
        echo 'false'
    elif [ -e /sys/block/$DEV/device/model ] &&
         grep -q DELLBOSS /sys/block/$DEV/device/model; then
        # in the case of BOSS, enter here
        echo 'false'
    else
        echo 'true'
    fi
}

for DM in $(ls /dev/dm-*); do
    DEV_PATH=$(cryptsetup status $DM | grep device | awk '{print $2}')
    if [ -z "$DEV_PATH" ]; then continue; fi
    if [ $(is_target_device $DEV_PATH) != 'true' ]; then continue; fi
    if ! $(echo i | gdisk $DM 2> /dev/null | grep "Partition name:" | grep -q "'$PART_NAME'"); then
        echo "create a partition on $DM (backed by $DEV_PATH)"
        echo "$GDISK_CMD" | gdisk $DM
    fi
    echo "update partition devmappings on $DM"
    kpartx -u $DM
done
