#!/bin/sh -u

PART_NAME=primary

is_target_device() {
    DEV=$(basename $1)
    if [ $DEV = 'vda' ] || [ $DEV = 'vdb' ]; then
        # in the case of qemu's system disks, enter here
        echo 'false'
    elif [ -e /sys/block/$DEV/device/model ] &&
         grep -q DELLBOSS /sys/block/$DEV/device/model; then
        # in the case of BOSS, enter here
        echo 'false'
    else
        echo 'true'
    fi
}

for DM in $(ls /dev/dm-*); do
    DEV_PATH=$(cryptsetup status $DM | grep device | awk '{print $2}')
    if [ -n "$DEV_PATH" ]; then
        if [ $(is_target_device $DEV_PATH) = 'true' ]; then
            if [ -n "$(parted -s $DM print 2> /dev/null | grep $PART_NAME)" ]; then
                echo "partition is already exists on $DM (backed by $DEV_PATH)"
                partprobe $DM
            else
                echo "create a partition on $DM (backed by $DEV_PATH)"
                parted -s -a optimal $DM -- mklabel gpt mkpart $PART_NAME 1MiB -0
            fi
        fi
    fi
done
