#!/bin/sh

DISK_DEV=$(dmsetup deps "/dev/$1" -o blkdevname | sed -e 's/.*(\(.*\))/\1/')
BASE_DEV=$(cryptsetup status "/dev/${DISK_DEV}" | grep device | awk '{print $2}')
UDEV_LINKS=$(udevadm info -q symlink -n ${BASE_DEV})
logger "$(basename $0) $1 DISK_DEV:$DISK_DEV BASE_DEV:$BASE_DEV"
logger "$(basename $0) $1 UDEV_LINKS:$UDEV_LINKS"

for symlink in $UDEV_LINKS; do
  case ${symlink} in
    disk/by-path/virtio-*)
      ;;
    disk/by-path/*)
      echo "CRYPT_BASE_PATH=${symlink#disk/by-path/}"
      ;;
  esac
done
mkdir -p /dev/crypt-part/by-path/
exit 0
