#!/bin/sh

SCRIPT_NAME=$(basename $0)
NAME=$1
UUID=$2

DISK_DEV=$(dmsetup deps -u $UUID -o blkdevname | sed -e 's/.*(\(.*\))/\1/')
BASE_DEV=$(cryptsetup status "/dev/${DISK_DEV}" | grep device | awk '{print $2}')
UDEV_LINKS=$(udevadm info -q symlink -n ${BASE_DEV})

logger "$SCRIPT_NAME $NAME DISK_DEV:$DISK_DEV BASE_DEV:$BASE_DEV"
logger "$SCRIPT_NAME $NAME UDEV_LINKS:$UDEV_LINKS"

for symlink in $UDEV_LINKS; do
  case ${symlink} in
    disk/by-path/virtio-*)
      ;;
    disk/by-path/*)
      echo "CRYPT_BASE_PATH=${symlink#disk/by-path/}"
      ;;
  esac
done
mkdir -p /dev/crypt-part/by-path/
exit 0
