apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - bgp_config.yaml
  - upstream.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cilium-operator
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cke.cybozu.com/rank: "2500"
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: cilium
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cke.cybozu.com/rank: "2500"
