apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: cilium
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cilium-operator
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hubble-relay
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources
