apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: internet-egress
spec:
  template:
    spec:
      containers:
        - name: unbound
          resources:
            requests:
              cpu: 25m
              memory: 170Mi
            limits:
              cpu: 250m
              memory: 1700Mi
