#!/bin/sh -e

SERVICES="node-exporter neco-updater neco-worker"
TIMERS="sabakan-state-setter"

configure() {
    systemctl daemon-reload
    for t in $TIMERS; do
        systemctl enable ${t}.timer
        systemctl start ${t}.timer
    done

    for s in $SERVICES; do
        systemctl enable ${s}.service
        systemctl start ${s}.service
    done

    /usr/bin/neco completion > /etc/bash_completion.d/neco
    /usr/bin/kubectl completion bash > /etc/bash_completion.d/kubectl
}

if test "$1" = "configure"; then
    configure
fi

exit 0
