#!/bin/sh -e

SERVICES="node-exporter neco-updater neco-worker sabakan-state-setter neco-rebooter cke cke-localproxy teleport-node"
TIMERS="docker-prune kill-old-login-sessions backup-cke-etcd export-unit-status"

configure() {
    # temporary code for transition
    if [ -f /etc/systemd/teleport-node.service ]; then
        systemctl stop teleport-node.service
        rm /etc/systemd/teleport-node.service
        rm -f /usr/local/bin/tctl /usr/local/bin/tsh /usr/local/bin/teleport /usr/local/bin/ckecli
    fi

    systemctl daemon-reload
    for t in $TIMERS; do
        systemctl enable ${t}.timer
        systemctl start ${t}.timer
    done

    for s in $SERVICES; do
        systemctl enable ${s}.service
        systemctl start ${s}.service
    done

    mkdir -p /etc/teleport
    /usr/bin/neco completion > /etc/bash_completion.d/neco
    /usr/bin/ckecli completion > /etc/bash_completion.d/ckecli
    /usr/bin/kubectl completion bash > /etc/bash_completion.d/kubectl
    /usr/bin/stern --completion bash > /etc/bash_completion.d/stern
    /usr/bin/argocd completion bash > /etc/bash_completion.d/argocd
}

if test "$1" = "configure"; then
    configure
fi

exit 0
