#!/bin/sh -e

SERVICES="neco-updater neco-worker node-exporter sabakan-state-setter ingress-watcher cke teleport-node"
TIMERS="rkt-gc kill-old-login-sessions backup-cke-etcd"

prerm() {
    for s in $SERVICES; do
        systemctl stop ${s}.service
        systemctl disable ${s}.service
    done

    for t in $TIMERS; do
        systemctl stop ${t}.timer
        systemctl disable ${t}.timer
    done
}

prerm

exit 0
