kind: ConfigMap
apiVersion: v1
metadata:
  name: squid
  namespace: internet-egress
data:
  squid.conf: |-
    acl neco_network src 10.64.0.0/12
    # Only allow cachemgr access from localhost
    http_access allow manager localhost
    http_access deny manager
    http_access allow neco_network
    http_access deny all
    http_port 3128
    cache_mem 6 GB
    maximum_object_size_in_memory 100 MB
    detect_broken_pconn on
    forwarded_for delete
    httpd_suppress_version_string on
    shutdown_lifetime 10 seconds
    pid_filename   none
    logfile_rotate 0
    access_log     stdio:/dev/stdout
    cache_log      stdio:/dev/stderr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-unbound
  namespace: internet-egress
data:
  unbound.conf: |
    server:
      do-daemonize: no
      interface: 0.0.0.0
      interface-automatic: yes
      access-control: 10.64.0.0/12 allow
      chroot: ""
      username: ""
      directory: "/etc/unbound"
      logfile: ""
      use-syslog: no
      log-time-ascii: yes
      log-queries: yes
      log-replies: yes
      log-local-actions: yes
      log-servfail: yes
      rrset-roundrobin: yes
      minimal-responses: yes
      extended-statistics: yes
      rrset-cache-size: 256m
      msg-cache-size: 256m
      pidfile: "/tmp/unbound.pid"
      infra-host-ttl: 60
      prefetch: yes
      root-hints: "/usr/local/unbound/etc/unbound/root.hints"
      trust-anchor-file: "/usr/local/unbound/etc/unbound/root.key"
    remote-control:
      control-enable: yes
      control-interface: 127.0.0.1
      control-use-cert: no
