kind: Deployment
apiVersion: apps/v1
metadata:
  name: squid
  namespace: internet-egress
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: squid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: squid
    spec:
      # system priority class cannot be specified for pods in namespaces
      # other than kube-system as of k8s 1.12.
      # see https://github.com/kubernetes/kubernetes/pull/65593
      #priorityClassName: system-cluster-critical
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node.cybozu.io/cluster-not-ready
          effect: NoExecute
          operator: Exists
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 127.0.0.1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - squid
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - squid
                topologyKey: "cke.cybozu.com/rack"
      containers:
        - name: squid
          image: ghcr.io/cybozu/squid
          args: ["-f", "/etc/squid-conf/squid.conf"]
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          volumeMounts:
            - mountPath: /var/spool/squid
              name: cache
            - mountPath: /etc/squid-conf
              name: config
          ports:
            - name: proxy
              containerPort: 3128
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          readinessProbe:
            tcpSocket:
              port: 3128
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 3128
            periodSeconds: 1
            initialDelaySeconds: 10
            failureThreshold: 6
        - name: unbound
          image: ghcr.io/cybozu/unbound
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/unbound/unbound.conf
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound
              readOnly: true
            - name: temporary-volume
              mountPath: /tmp
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 53
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 53
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 6
        - name: exporter
          image: ghcr.io/cybozu/unbound_exporter
          imagePullPolicy: IfNotPresent
          args:
            # empty string = don't use cert
            - --unbound.ca=
            - --unbound.cert=
          ports:
            - containerPort: 9167
              name: metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsGroup: 10000
          resources:
            requests:
              cpu: 100m
        - name: squid-exporter
          image: ghcr.io/cybozu/squid-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
              name: squid-metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsUser: 10000
            runAsGroup: 10000
      volumes:
        - name: cache
          emptyDir: {}
        - name: config
          configMap:
            name: squid
        - name: config-volume
          configMap:
            name: local-unbound
            items:
              - key: unbound.conf
                path: unbound.conf
        - name: temporary-volume
          emptyDir: {}
