apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../v2
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/tolerations/-
      value:
        effect: NoExecute
        key: node.cybozu.io/cluster-not-ready
        operator: Exists
    - op: add
      path: /metadata/annotations
      value:
        cke.cybozu.com/rank: "2600"
  target:
    group: apps
    kind: Deployment
    name: coil-controller
    version: v1
- path: daemonset.yaml
