#!/bin/sh

# eth0 -> internet
# eth1 -> BMC
iptables -t nat -A POSTROUTING -o eth0 -s 172.19.0.0/24 -j MASQUERADE
iptables -t nat -A POSTROUTING -o eth0 -s 172.16.4.64/29 -j MASQUERADE
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
