package gcp

var artifacts = artifactSet{
	goVersion:           "1.12.5",
	rktVersion:          "1.30.0",
	etcdVersion:         "3.3.13",
	placematVersion:     "1.3.5",
	customUbuntuVersion: "20190607",
	coreOSVersion:       "2079.5.1",
	ctVersion:           "0.9.0",
	baseImage:           "ubuntu-1804-bionic-v20190429",
	baseImageProject:    "ubuntu-os-cloud",
	debPackages: []string{
		"git",
		"build-essential",
		"less",
		"wget",
		"systemd-container",
		"lldpd",
		"qemu",
		"qemu-kvm",
		"socat",
		"picocom",
		"cloud-utils",
		"xauth",
		"bash-completion",
		"dbus",
		"jq",
		"libgpgme11",
		"freeipmi-tools",
		"unzip",
		// required by building container image
		"skopeo",
		"podman",
		"cri-o-runc",
		"cri-o-1.13",
		"fakeroot",
		"btrfs-tools",
		// required by building neco
		"libdevmapper-dev",
		"libgpgme-dev",
		"libostree-dev",
		// required by building containerd
		"libseccomp-dev",
	},
}
