#!/bin/sh -ex

IMAGE=$1
shift

NBD=/dev/nbd0
NBDp1=/dev/mapper/nbd0p1

modprobe nbd
qemu-nbd -c $NBD $IMAGE
trap "kpartx -d $NBD 2>/dev/null; qemu-nbd -d $NBD" INT QUIT TERM 0

# resize part1
growpart $NBD 1

# copy files
kpartx -a $NBD
sleep 2
mount $NBDp1 /mnt
mkdir /mnt/extras
cp -a "$@" /mnt/extras
chroot /mnt systemctl disable systemd-resolved.service
rm -f /mnt/etc/resolv.conf
chroot /mnt sed -i '/127.0.0.1 localhost/a 127.0.1.1 boot' /etc/hosts
chroot /mnt dpkg -r --force-depends systemd-timesyncd
chroot /mnt sh -c "dpkg -i /extras/*.deb"
sync
umount /mnt
