#!/bin/sh -ex

IMAGE=$1
shift

modprobe nbd

for nbd_dev in /sys/devices/virtual/block/nbd*;
do
    if [ -e ${nbd_dev}/pid ]
    then
        continue
    else
        NBD="/dev/$(basename $nbd_dev)"
        NBDp1="/dev/mapper/$(basename $nbd_dev)p1"
    fi
    if qemu-nbd -c $NBD $IMAGE; then break; fi
    echo "$NBD is not available. Try to use the next released device."
    NBD=""
    NBDp1=""
    sleep 1s
done
if [ -z "$NBD" ]; then
    exit 1
fi
trap "kpartx -d $NBD 2>/dev/null; qemu-nbd -d $NBD" INT QUIT TERM 0

# resize part1
growpart $NBD 1

# copy files
kpartx -a $NBD
sleep 2
mount $NBDp1 /mnt
mkdir /mnt/extras
cp -a "$@" /mnt/extras
chroot /mnt systemctl disable systemd-resolved.service
rm -f /mnt/etc/resolv.conf
chroot /mnt sed -i '/127.0.0.1 localhost/a 127.0.1.1 boot' /etc/hosts
chroot /mnt dpkg -r --force-depends systemd-timesyncd
chroot /mnt sh -c "dpkg -i /extras/*.deb"
sync
umount /mnt
