#!/bin/sh -ex

IMAGE=$1
shift

losetup -f $IMAGE
LO=$(sudo losetup -j $IMAGE | cut -d: -f1)
LOp1=/dev/mapper/${LO##*/}p1
trap "kpartx -d $LO 2>/dev/null; losetup -d $LO" INT QUIT TERM 0

# resize part1
growpart $LO 1
kpartx -a $LO
mount $LOp1 /mnt

# copy files
mkdir /mnt/extras
cp -a "$@" /mnt/extras
chroot /mnt systemctl disable systemd-resolved.service
rm -f /mnt/etc/resolv.conf
chroot /mnt sed -i '/127.0.0.1 localhost/a 127.0.1.1 boot' /etc/hosts
chroot /mnt dpkg -r --force-depends systemd-timesyncd
chroot /mnt sh -c "dpkg -i /extras/*.deb"
sync
umount /mnt
